apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    project: expense
    environment: dev
    tier: web
spec: 
  replicas: 3
  selector:
    matchLabels:
      project: expense
      environment: dev
      tier: web
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        tier: web
    spec:
      containers:
        - name: frontend
          image: cekharch/frontend:v1
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
  labels:
    project: expense
    environment: dev
    tier: web
spec:
  type: LoadBalancer
  selector:
    project: expense
    environment: dev
    tier: web
  ports:
    - port: 80
      targetPort: 80