apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    environment: dev
    tier: api
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    environment: dev
    tier: api
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      environment: dev
      tier: api
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        tier: api
    spec:
      containers:
        - name: backend
          image: cekharch/backend:v1
          envFrom:
            - configMapRef:
                name: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    environment: dev
    tier: api
spec:
  selector:
    project: expense
    environment: dev
    tier: api
  ports:
    - port: 8080
      targetPort: 8080